// GENERAL
export const ERROR = 'ERROR'
export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'
export const CONNECT_WALLET = 'CONNECT_WALLET'

export const CONFIGURE = 'CONFIGURE'
export const ACCOUNT_CONFIGURED = 'ACCOUNT_CONFIGURED'

export const CONFIGURE_NETWORK_LIST = 'CONFIGURE_NETWORK_LIST'
export const NETWORK_LIST_CONFIGURED = 'NETWORK_LIST_CONFIGURED'

export const STORE_UPDATED = 'STORE_UPDATED'
export const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED'
export const TRY_CONNECT_WALLET = 'TRY_CONNECT_WALLET'

export const TX_SUBMITTED = 'TX_SUBMITTED'
